"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import Link from "next/link";
import { CalendarDays, MapPin, Trophy } from "lucide-react";
import { PublicNav } from "@/components/public-nav";
import { supabase } from "@/lib/supabase";
type Tournament = { id: string; name: string; logo_url: string | null; venue: string | null; start_date: string | null; status: string | null; overs: number | null };
export default function PublicTournamentsPage() { const [rows, setRows] = useState<Tournament[]>([]); useEffect(() => { void (async () => { const { data } = await supabase.from("tournaments").select("id,name,logo_url,venue,start_date,status,overs").is("deleted_at", null).order("start_date", { ascending: false }); setRows(data || []); })(); }, []); return <><PublicNav /><main className="mx-auto max-w-6xl p-4 sm:p-7"><p className="text-sm font-black uppercase tracking-widest text-primary">Competition centre</p><h1 className="mt-1 text-3xl font-black text-foreground">Tournaments</h1><p className="mt-2 text-muted-foreground">Explore fixtures, teams, standings and tournament leaders.</p><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rows.map((item) => <Link key={item.id} href={`/tournaments/${item.id}`} className="group rounded-2xl border border-border bg-card p-5 text-foreground shadow-sm transition hover:-translate-y-1 hover:border-primary/50 hover:shadow-xl"><div className="flex items-center gap-4">{item.logo_url ? <Image unoptimized width={128} height={128} src={item.logo_url} alt="" className="h-16 w-16 rounded-2xl bg-white object-contain p-1" /> : <span className="grid h-16 w-16 place-items-center rounded-2xl bg-primary/10"><Trophy className="h-8 w-8 text-primary" /></span>}<div className="min-w-0"><span className="rounded-full bg-primary/10 px-2 py-1 text-[.65rem] font-black uppercase text-primary">{displayStatus(item)}</span><h2 className="mt-2 line-clamp-2 text-lg font-black">{item.name}</h2></div></div><div className="mt-5 space-y-2 text-sm text-muted-foreground"><p className="flex items-center gap-2"><MapPin className="h-4 w-4" />{item.venue || "Venue TBC"}</p><p className="flex items-center gap-2"><CalendarDays className="h-4 w-4" />{item.start_date || "Date TBC"} · {item.overs || "—"} overs</p></div></Link>)}</div></main></>; }
function displayStatus(item:Tournament){if(item.status!=="upcoming"||!item.start_date)return item.status||"upcoming";const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Colombo"}).format(new Date());return item.start_date<=today?"ongoing":"upcoming"}
