"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, Crown, ShieldCheck } from "lucide-react";
import { PublicNav } from "@/components/public-nav";
import { supabase } from "@/lib/supabase";
type Match={id:string;team_a_id:string;team_b_id:string;tournament_id:string;match_date:string|null;match_time:string|null;ground:string|null}; type Team={id:string;name:string;logo_url:string|null}; type Player={id:string;name:string;photo_url:string|null;playing_role:string|null}; type Squad={team_id:string;player_id:string;is_captain:boolean};
export default function PublicTeamSheetPage(){const{id}=useParams<{id:string}>();const[match,setMatch]=useState<Match|null>(null);const[teams,setTeams]=useState<Team[]>([]);const[players,setPlayers]=useState<Player[]>([]);const[squad,setSquad]=useState<Squad[]>([]);useEffect(()=>{if(!id)return;void(async()=>{const m=await supabase.from("matches").select("id,team_a_id,team_b_id,tournament_id,match_date,match_time,ground").eq("id",id).maybeSingle();if(!m.data)return;setMatch(m.data);const[t,p,s]=await Promise.all([supabase.from("teams").select("id,name,logo_url").in("id",[m.data.team_a_id,m.data.team_b_id]),supabase.from("players").select("id,name,photo_url,playing_role").in("team_id",[m.data.team_a_id,m.data.team_b_id]),supabase.from("match_squads").select("team_id,player_id,is_captain").eq("match_id",id)]);setTeams(t.data||[]);setPlayers(p.data||[]);setSquad(s.data||[]);})();},[id]);if(!match)return <><PublicNav/><main className="p-10 text-center text-foreground">Loading Playing XI…</main></>;const team=(teamId:string)=>teams.find(t=>t.id===teamId)!;return <><PublicNav/><main className="mx-auto max-w-5xl space-y-5 p-4 sm:p-7"><Link href={`/match/${id}`} className="inline-flex items-center gap-2 font-bold text-primary"><ArrowLeft className="h-4 w-4"/>Match centre</Link><header className="text-center text-foreground"><p className="text-xs font-black uppercase tracking-[.2em] text-primary">Official team sheet</p><h1 className="mt-2 text-3xl font-black">Playing XI</h1><p className="mt-2 text-sm text-muted-foreground">{match.match_date} {match.match_time?`· ${match.match_time}`:""} {match.ground?`· ${match.ground}`:""}</p></header><div className="grid gap-5 md:grid-cols-2">{[match.team_a_id,match.team_b_id].map(teamId=><TeamSquad key={teamId} team={team(teamId)} rows={squad.filter(row=>row.team_id===teamId)} players={players}/>)}</div></main></>}
function TeamSquad({team,rows,players}:{team:Team;rows:Squad[];players:Player[]}){return <section className="overflow-hidden rounded-2xl border border-border bg-card text-foreground shadow-sm"><header className="flex items-center gap-3 border-b border-border p-4">{team?.logo_url?<Image unoptimized width={128} height={128} src={team.logo_url} alt="" className="h-12 w-12 rounded-full bg-white object-contain"/>:<ShieldCheck className="h-10 w-10 text-primary"/>}<h2 className="text-lg font-black">{team?.name||"Team"}</h2></header><div className="divide-y divide-border">{rows.map((row,index)=>{const p=players.find(item=>item.id===row.player_id);if(!p)return null;return <Link href={`/players/${p.id}`} key={row.player_id} className="flex items-center gap-3 p-3 hover:bg-muted/50"><span className="w-5 text-center text-xs font-black text-muted-foreground">{index+1}</span>{p.photo_url?<Image unoptimized width={128} height={128} src={p.photo_url} alt="" className="h-10 w-10 rounded-full object-cover"/>:<span className="grid h-10 w-10 place-items-center rounded-full bg-primary/10 font-black text-primary">{p.name[0]}</span>}<span className="min-w-0 flex-1"><span className="flex items-center gap-2 truncate font-black">{p.name}{row.is_captain&&<Crown className="h-4 w-4 shrink-0 text-amber-500"/>}</span><span className="text-xs text-muted-foreground">{roleSymbol(p.playing_role)} {p.playing_role||"Player"}</span></span></Link>})}{!rows.length&&<p className="p-8 text-center text-sm text-muted-foreground">Playing XI has not been published yet.</p>}</div></section>}
function roleSymbol(role:string|null){const v=(role||"").toLowerCase();return v.includes("wicket")?"🧤":v.includes("all")?"🏏🔴":v.includes("bowl")?"🔴":"🏏"}
